Repository unjs/website, pull requests merged in 2023-08, with the labels that each got.

#31 feat: add search
  .markdownlintignore
  app.config.ts
  assets/app.css
  components/app/AppHeader.vue
  components/app/AppSearch.vue
  components/app/search/AppSearchGroup.vue
  components/app/search/AppSearchGroupItem.vue
  composables/useSearch.ts
  content/1.packages.md
  content/4.packages/jiti.md
  content/4.packages/unenv.md
  content/4.packages/unplugin.md
  content/4.packages/webpackbar.md
  nuxt.config.ts
  package.json
  pnpm-lock.yaml
  scripts/repos-packages.ts
  server/api/search.ts
  server/utils/search.ts
  types/search.ts
Labels: enhancement

#46 fix: typo in cookie-es description
  content/4.packages/cookie-es.md
Labels: typo

#72 fix: optimize blog styles
  components/content/AnotherArticle.vue
  components/content/ProseTable.vue
  components/content/ProseTbody.vue
  components/content/ProseThead.vue
  layouts/blog.vue
  uno.config.ts
Labels: enhancement

#70 feat: add blog for nitro 2.6 announcement
  content/5.blog/2023-08-25-nitro-2.6.md
Labels: content
